### PR TITLE
fix: patch rcgen-0.13.3

### PR DESCRIPTION
**Pull request by junkurihara**
Hi! Since the upsate of `rcgen`-0.13.3, the test fails as reported in #73.

The reason is that the signature of `signed_by` is changed from `Certificate` to `AsRef<CertificateParams>`, and that `self.ca_cert` is `Arc`-ed in `TestCache`.

https://github.com/FlorianUekermann/rustls-acme/blob/a02f1b940bdf9a3f8ae1a9034c1c59b69466437d/src/caches/test.rs#L71

So the solution is to simply `deref` the object. This PR simply solves the compilation error of the test code.

### CODE REVIEW

**Comment by junkurihara** [comment]
The change may be going to be yanked. Then I will close this :-) https://github.com/FlorianUekermann/rustls-acme/issues/73#issuecomment-2726478766

**Comment by junkurihara** [comment]
The update was yanked. I close this PR. Sorry for the bothering!
