### ISSUE TITLE
Error after upgrading rustls-acme to 0.8 and rustls to 0.22

### ISSUE THREAD

**Issue by blueowlgreenfish** [FlorianUekermann/rustls-acme#56]
I upgraded `rustls-acme` to 0.8 and `rustls` to 0.22, but I'm getting a compiler error.

> error[E0432]: unresolved import `rustls`
 --> /home/t/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustls-acme-0.8.0/src/axum.rs:4:5
  |
4 | use rustls::ServerConfig;
  |     ^^^^^^ help: a similar path exists: `futures_rustls::rustls`

> error[E0433]: failed to resolve: use of undeclared crate or module `rustls`
   --> /home/t/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustls-acme-0.8.0/src/state.rs:134:52
    |
134 |     pub fn axum_acceptor(&self, rustls_config: Arc<rustls::ServerConfig>) -> crate::axum::AxumAcceptor {
    |                                                    ^^^^^^ use of undeclared crate or module `rustls`
    |
help: consider importing one of these items
    |
1   + use crate::futures_rustls::rustls;
    |
1   + use futures_rustls::rustls;

**Comment by FlorianUekermann** [comment]
Thanks for reporting this. Sorry about that. Not sure how the axum feature slipped through, when I did the rustls 0.22 changes. I release 0.8.1, which fixes this error.
